name: Release PHP Project

on:
  push:
    tags:
      - 'v*'  # Se ejecuta cuando haces push de un tag como v1.0.0

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
        working-directory: ./DocuCodeAI

      - name: Create the release archive
        run: |
          mkdir -p release
          tar -czf release/my-php-project-${GITHUB_REF##*/}.tar.gz *
        working-directory: ./DocuCodeAI

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION_TAG=${GITHUB_REF##*/}
          gh release create $VERSION_TAG DocuCodeAI/release/my-php-project-${VERSION_TAG}.tar.gz --title "Release ${VERSION_TAG}" --notes "Release notes for version ${VERSION_TAG}"
